### ISSUE TITLE
Clean up pedestrian_tracker_lib

### ISSUE THREAD

**Issue by gsaponaro** [vislab-tecnico-lisboa/pedestrian_tracker_lib#1]
Hi @joao-avelino,
This repository (**pedestrian_tracker_lib**) seems empty.
Do you still plan about committing some code here, or shall I delete it? :)
No hurry, I'm just curious to know. Thanks.

**Comment by joao-avelino** [comment]
Sure, delete it for now. I will recreate it if needed.

Thanks!

**Comment by gsaponaro** [comment]
OK. Deleting the empty **pedestrian_tracker_lib** repo for now... Ciao!
